### PR TITLE
Allow usage of the calendar for specific periods

### PR DESCRIPTION
**Pull request by Paul-DS**
Following the requests for this 2 features:
- Display only X months in the calendar (#26, Paul-DS/bootstrap-year-calendar#19, Paul-DS/bootstrap-year-calendar#101, Paul-DS/bootstrap-year-calendar#120)
- Change the starting month of the calendar (#30, Paul-DS/bootstrap-year-calendar#18, Paul-DS/bootstrap-year-calendar#43, Paul-DS/bootstrap-year-calendar#60)

This PR implement 2 options:
- `startDate`: Allow to define the first month displayed in the calendar
- `numberMonthsDisplayed` Allow to define the number of months displayed in the calendar

# Examples

These options allow you to do the following:

## Display a full year starting from a specific month

With parameters:
- `startDate: new Date(2020, 8, 1)`

Result:
image

## Display only X months

With parameters:
- `numberMonthsDisplayed: 3`

Result:
image

With parameters:
- `startDate: new Date(2020, 3, 1)`
- `numberMonthsDisplayed: 1`

Result:
image

# TODO

- [x] Update the `dataSource` option to pass the `startDate` and `endDate` parameters
- [x] Update the comments to specify the order of priority between `startDate` and `startYear`
- [x] Update the comments to specify the condition of usage of `yearChanged` event, the `getYear`/`setYear` methods, etc...
- [ ] Test all functionalities to unsure there is no regression
- [x] Add specific unit tests

# Breaking changes :warning:

The first parameter of the dataSource function is now `{ year, startDate, endDate }` instead of just `year`.

Example:
```
new Calendar('#calendar', {
    dataSource: function(period) {
        console.log(`Year: ${period.year}`);
        console.log(`Period displayed: ${period.startDate} - ${period.endDate}`);
        return ...;
    }
});
```

# How to test

Use the `@next` version of the package:
- With NPM: `npm install js-year-calendar@next`
- With CDN: `<script src="https://unpkg.com/js-year-calendar@next/dist/js-year-calendar.min.js"></script>`

# Additional informations

This is an additional feature , so it shouldn't break the current usage of the calendar (using the basic option`startYear`).

The `startDate` option override the `startYear` option.
The `yearChanged` event, and the `getYear` and `setYear` method are available only if the `startDate` and `numberMonthsDisplayed` options are not used.

### CODE REVIEW

**Comment by Paul-DS** [comment]
This functionality will be released in the v1.1.0.
I'll provide a beta version as soon as I'll publish the v1.0.2, so you can all test this feature.

Given the lot of modifications needed for this feature, I will need a lot of testing from current users to check that there is no regression.

I'm open to any remark on the current implementation.

**Comment by sarveshraval** [comment]
Hi @Paul-DS I tested the functionality in alpha version , is it available in the stable version 1.1 or 1.2 ?

**Comment by PieterDJK** [comment]
Hi @Paul-DS,

First of all, great calendar! I tried to test this new functionality, but I have troubles with the dataSource.
I have tested it with your github API and that works fine, but I use a Json Object (or Array) as input source instead.
In the bootstrap version that worked fine, but in this version I'm probably doing something wrong (as I'm not a JavaScript expert). 
I hope you can help me with this.

If I use your example code of the dataSource usage it works fine:
******************************************************************
...
    dataSource: function(year) {
      // Load data from GitHub API
      return fetch(`https://api.github.com/search/issues?q=repo:Paul-DS/bootstrap-year-calendar%20created:2020-01-01..2020-12-31`)
        .then(result => result.json())
        .then(result => {
          if (result.items) {
            return result.items.map(r => ({
              startDate: new Date(r.created_at),
              endDate: new Date(r.created_at),
              name: '#' + r.number + ' - ' + r.title,
              details: r.comments + ' comments', 
            }));
          }          
          return [];
        });
      },
...
******************************************************************

Here is my version where "CalendarData" is the Json Object (see example below). 
 
const calendar = new Calendar(('#controlAddIn'),
  {    
    language: 'nl',
    enableRangeSelection:true,
    enableContextMenu: true, 
    numberMonthsDisplayed: 1,
    startDate: new Date(2020,1,1), 

    dataSource: function(period) {
          if (CalendarData.dataSource) {
            return CalendarData.dataSource.map(r => ({
              startDate: parseStringToDate(r.startDate), 
              endDate: parseStringToDate(r.endDate), 
              name: r.name,
              color : r.color
            }));
          }
          return [];
    }
  });
  
function parseStringToDate(dateString) {
  // get year, month and day
  var ymd = dateString.split(" ")[0].split("-");
  var mydate = new Date(parseInt(ymd[0]), parseInt(ymd[1])-1, parseInt(ymd[2]))
  return mydate;
}

************************************************************************************
example of the "CalendarData" Json Object:
{"dataSource":[
{"startDate":"2020-01-01","endDate":"2020-01-01","name":"","color":"#E89E63"},
{"startDate":"2020-01-28","endDate":"2020-01-28","name":"O000777","color":"#75D8E7"},
{"startDate":"2020-01-29","endDate":"2020-01-29","name":"O000777","color":"#75D8E7"}
]}

**Comment by JJZolper** [comment]
Would love to use this feature in my application for my client. Be happy to try it out at a minimum and see how things go. I think numberMonthsDisplayed makes a lot of sense and yeah just being able to control which is the first month right by setting the date. Sounds great to me.

Only thought that may be nice is just being able to control this dynamically. Say the user has the 12 month calendar showing and wants to change to 3 month. If you are able to provide a method where I can call and set those 3 parameters and cause the calendar to re-render that would be slick. But I understand if that could be a lot more work on top of what you are already doing. Sometimes like other calendars i.e. Google they want to be able to switch between views, making that seamless is just my suggestion and would be a nice to have for sure.

Other than that as long as the dataSource works as expected like you already mentioned I think when the calendar re-renders that's the main thing I can think of right now. I'll think more.

**Comment by JJZolper** [comment]
@Paul-DS is there a potential ETA on this by the way? I think my clients would be excited for the flexible partial month view. That kind of ability to flex between either a full calendar year or partial would be ideal for their needs. I've found ways to rigger a re-draw by setting the dataSource dynamically, and if this worked with similar methods on the elements that would be great. Happy to try to help push things forward where I can.

**Comment by basilgohar** [comment]
I was about to put in a request for this kind of a feature as well and then I saw the reference to this PR.  I'm calling it a night for now but I may try this out and report back here on my own success.

**Comment by Paul-DS** [comment]
I published a new version with some minor modifications.

@sarveshraval Did you find any bug while testing this new functionality ?

@PieterDJK Your code seems to be working, but the data are displayed in January, and you're opening the calendar in February (`startDate: new Date(2020,1,1)`). Change the start date to `startDate: new Date(2020,0,1)` to make it work

@JJZolper you can now use the `setStartDate` and `setNumberMonthsDisplayed` to change the displayed period dynamically.

Concerning the ETA, I'll wait for about a week to get more feedback, and then publish a new release (2.0.0) with this functionality.

Thank you all for your feedback.

**Comment by PieterDJK** [comment]
@Paul-DS, thanks for your reaction. I already tried that, my example code was not correct, sorry.
I have tested it again for a whole year with the code below:
`**********************************************************
const calendar = new Calendar(('#controlAddIn'),
 {    
   language: 'nl',
   enableRangeSelection:true,
   enableContextMenu: true, 
   numberMonthsDisplayed: 12,
   startDate: new Date(2020,0,1), 
   dataSource: function(period) {
         if (CalendarData) {
           return CalendarData.map(r => ({
             startDate: parseStringToDate(r.startDate), 
             endDate: parseStringToDate(r.endDate), 
             name: r.name,
             color : r.color
           }));
         }
         return [];
   }
 });
 
function parseStringToDate(dateString) {
 // get year, month and day
 var ymd = dateString.split(" ")[0].split("-");
 var mydate = new Date(parseInt(ymd[0]), parseInt(ymd[1])-1, parseInt(ymd[2]))
 return mydate;
}
` **********************************************************
where CalendarData is the below Json Array:

[{"startDate":"2020-01-01","endDate":"2020-01-01","name":"","color":"#E89E63"},{"startDate":"2020-01-28","endDate":"2020-01-28","name":"O000777","color":"#75D8E7"},{"startDate":"2020-01-29","endDate":"2020-01-29","name":"O000777","color":"#75D8E7"},{"startDate":"2020-02-04","endDate":"2020-02-04","name":"O000777","color":"#75D8E7"},{"startDate":"2020-02-20","endDate":"2020-02-20","name":"O000777","color":"#75D8E7"},{"startDate":"2020-03-03","endDate":"2020-03-03","name":"O000777","color":"#75D8E7"},{"startDate":"2020-03-09","endDate":"2020-03-09","name":"O000777","color":"#75D8E7"},{"startDate":"2020-04-01","endDate":"2020-04-01","name":"","color":"#E97768"},{"startDate":"2020-04-07","endDate":"2020-04-07","name":"O000827","color":"#75D8E7"},{"startDate":"2020-04-27","endDate":"2020-04-27","name":"","color":"#E89E63"},{"startDate":"2020-05-05","endDate":"2020-05-05","name":"","color":"#E89E63"},{"startDate":"2020-05-09","endDate":"2020-05-09","name":"","color":"#E97768"},{"startDate":"2020-05-10","endDate":"2020-05-10","name":"O000828","color":"#75D8E7"},{"startDate":"2020-05-31","endDate":"2020-05-31","name":"","color":"#E89E63"},{"startDate":"2020-06-01","endDate":"2020-06-01","name":"","color":"#E89E63"},{"startDate":"2020-06-03","endDate":"2020-06-03","name":"O000898","color":"#75D8E7"},{"startDate":"2020-06-13","endDate":"2020-06-13","name":"O000899","color":"#75D8E7"},{"startDate":"2020-07-24","endDate":"2020-07-24","name":"1x per week vrijdag","color":"#E97768"},{"startDate":"2020-07-31","endDate":"2020-07-31","name":"1x per week vrijdag","color":"#E97768"},{"startDate":"2020-08-07","endDate":"2020-08-07","name":"1x per week vrijdag","color":"#E97768"},{"startDate":"2020-08-28","endDate":"2020-08-28","name":"1x per week vrijdag","color":"#E97768"},{"startDate":"2020-09-04","endDate":"2020-09-04","name":"1x per week vrijdag","color":"#E97768"},{"startDate":"2020-09-25","endDate":"2020-09-25","name":"1x per week vrijdag","color":"#E97768"},{"startDate":"2020-10-02","endDate":"2020-10-02","name":"1x per week vrijdag","color":"#E97768"},{"startDate":"2020-10-30","endDate":"2020-10-30","name":"1x per week vrijdag","color":"#E97768"},{"startDate":"2020-11-06","endDate":"2020-11-06","name":"1x per week vrijdag","color":"#E97768"},{"startDate":"2020-11-27","endDate":"2020-11-27","name":"1x per week vrijdag","color":"#E97768"},{"startDate":"2020-12-04","endDate":"2020-12-04","name":"1x per week vrijdag","color":"#E97768"},{"startDate":"2020-12-26","endDate":"2020-12-26","name":"","color":"#E89E63"}]

The result is an empty calendar of the whole year.
Any other idea?

**Comment by JJZolper** [comment]
I tested this out and didn't see any issues either. Are there some other PR's this is going into a major release? Or will this be be merged into latest soon? Not sure how you plan to release @Paul-DS .

**Comment by JJZolper** [comment]
In now implementing this for my calendar I had a thought or question. It's amazing to be able to set how many months are displayed. I think I understand the concept of the startDate or first month to show. For my needs though I basically want to show up until a certain month. So basically you could almost call it an EndDate in your terms. So the last month shown would be the current or actual real month of the year. Does that make sense @Paul-DS ?

I can calculate by subtracting months based on the number of months shown in order to figure out which month ends up being the start to give the proper end month, but I was wondering is setting the startDate with a method after the calendar has been initialized even possible in your existing constructs? I feel like it could be because we do do things like set the data source after initialization so it would be the same concept but for driving the month.

I won't be overly greedy and ask for yet another way to drive which months are shown inside the collection of number of months but as long as I can change which months are in the number of months I'd be set.

If I found a way to shift that calculation everything else looks good though and I'd be excited about an official release.

**Comment by JJZolper** [comment]
I need to change the color of the day or box clicked while also using the new setNumberMonthsDisplayed(). I was able to figure out a way to do this in a more complicated way below. spikesData contains the data for the entire calendar.

        clickDay: function(e) {

            clickedDay = convertDateToStrDashed(e.date);
            console.log(e);

            if((selectedDay.date != clickedDay) && (Array.isArray(e.events) && e.events.length > 0)) {
            
                // Reset previous selected day, if it had been set
                if(selectedDay.element) {
                    // Reset prior selections 
                    document.getElementById('calendar').querySelectorAll('.day-start').forEach(function(el) {
                        el.style.backgroundColor = 'rgb(' + [86,187,85,1].join(',') + ')';
                    })

                    // Data set
                    spikesData.forEach(function (item, index) {
                        if(item.spike_date == selectedDay.date) {
                            item.color = 'rgb(' + [86,187,85,1].join(',') + ')';
                        }
                    });
                }

                // Set new selected day
                e.element.style.backgroundColor = 'rgb(' + [0,128,128,1].join(',') + ')';
                spikesData.forEach(function (item, index) {
                    if(item.spike_date == clickedDay) {
                        item.color = 'rgb(' + [0,128,128,1].join(',') + ')';
                    }
                });

                selectedDay.date = clickedDay;
                selectedDay.element = e.element;
                
            }

        },


    $("#periodSelector ul li").click(function(){
        var monthOption = $(this).text();

        var modDate = new Date();
        if(monthOption == '3 Months') {
            // Smaller box
            $("#calendarBox").css("width", "700px");

            modDate.setMonth(today.getMonth() - 3);

            calendar.setStartDate(modDate);
            calendar.setNumberMonthsDisplayed(3);

            calendar.setDataSource(spikesData);
        } else if(monthOption == '6 Months') {
            // Full width box
            $("#calendarBox").css("width", "100%");

            modDate.setMonth(today.getMonth() - 6);

            calendar.setStartDate(modDate);
            calendar.setNumberMonthsDisplayed(6);

            calendar.setDataSource(spikesData);
        } else if(monthOption == '12 Months') {
            // Full width box
            $("#calendarBox").css("width", "100%");

            modDate.setMonth(today.getMonth() - 12);

            calendar.setStartDate(modDate);
            calendar.setNumberMonthsDisplayed(12);

            calendar.setDataSource(spikesData);
        }

        $("#period_selected").text(monthOption);
        $("#periodSelector ul").removeClass("active");
    });

I change the colors of the objects for the calendar on a per date basis as they click the day. I also set the element itself sometimes if needed. When a redraw occurs from the setNumberMonthsDisplayed() and setStartDate() it requires passing via the data and changing again after. Event though I was able to workaround things is this something that would be easy to add at some point @Paul-DS?

**Comment by Cavva79** [comment]
Hi @Paul-DS,
I'm approaching to js-year-calendar, this feature it is foundamental for a project I'm in.
I'm trying to show a period of time from 11 nov 2020 to 10 nov 2021. Obviusly it is an year but spans on 13 months.
I think this
https://github.com/year-calendar/js-year-calendar/blob/5e0e89f6ff882433d06ecae09dcbf82c00ee22fd/src/ts/js-year-calendar.ts#L235
could be easy switched to
```javascript
			numberMonthsDisplayed: !isNaN(parseInt(opt.numberMonthsDisplayed)) && opt.numberMonthsDisplayed > 0 ? parseInt(opt.numberMonthsDisplayed) : 12,
```
to allow more than 12 months or try to implement intermediate startDate.

**Comment by Paul-DS** [comment]
Sorry guys for the delay.

@JJZolper I don't see your point exactly, can you provide a CodePen (or similar) example.

@Cavva79 Can you open a dedicated issue for this feature ? I'm gonna merge this PR, so I'll handle your request separately.

**Comment by Paul-DS** [comment]
The feature is available in v2.0.0

**Comment by Cavva79** [comment]
Hi @Paul-DS,
I just opened the issue #73 you asked some days ago.
thank you for your help

**Comment by manuelfrancisc** [comment]
Hi, @Paul-DS 

u ok?

i have  a bug using de calendar with asp net core 5  and vue js 

<script src="https://unpkg.com/js-year-calendar@latest/dist/js-year-calendar.min.js"></script>
<script src="https://unpkg.com/js-year-calendar@latest/locales/js-year-calendar.pt.js"></script>

<script>
    new Calendar('.calendar', {
        style: 'background',
        minDate: new Date()
    })
</script>



image

**Pull request merged**
